-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 18:36:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`GuestLogin_anuvindp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GuestLogin_anuvindp` (
  `guest_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `contact_number` VARCHAR(45) NOT NULL,
  `email_id` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`guest_id`),
  UNIQUE INDEX `guest_id_UNIQUE` (`guest_id` ASC) VISIBLE,
  UNIQUE INDEX `contact_number_UNIQUE` (`contact_number` ASC) VISIBLE,
  UNIQUE INDEX `email_id_UNIQUE` (`email_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Hostlogin_AnuvindP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hostlogin_AnuvindP` (
  `host_id` INT NOT NULL,
  `host_first_name` VARCHAR(45) NOT NULL,
  `host_last_name` VARCHAR(45) NOT NULL,
  `host_email` VARCHAR(45) NOT NULL,
  `host_dob` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`host_id`),
  UNIQUE INDEX `host_email_UNIQUE` (`host_email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Properties_AnuvindP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Properties_AnuvindP` (
  `property_id` INT NOT NULL,
  `property_name` VARCHAR(45) NULL DEFAULT NULL,
  `property_type` VARCHAR(45) NOT NULL,
  `addressline_1` VARCHAR(45) NOT NULL,
  `addressline_2` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `county` VARCHAR(45) NOT NULL,
  `zip_code` INT NOT NULL,
  `max_accomadate` INT NOT NULL,
  `rate` INT NOT NULL,
  `cnt_bed` INT NOT NULL,
  `cnt_bath` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `host_id_fk` INT NOT NULL,
  PRIMARY KEY (`property_id`),
  INDEX `fk_Properties_AnuvindP_HostLogin_AnuvindP1_idx` (`host_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_Properties_AnuvindP_HostLogin_AnuvindP1`
    FOREIGN KEY (`host_id_fk`)
    REFERENCES `mydb`.`Hostlogin_AnuvindP` (`host_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Booking_AnuvindP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Booking_AnuvindP` (
  `booking_id` INT NOT NULL,
  `booking_status` VARCHAR(45) NULL DEFAULT NULL,
  `host_id` INT NOT NULL,
  `check_in_date` DATETIME NOT NULL,
  `check_out_date` DATETIME NOT NULL,
  `booking_date` DATE NOT NULL,
  `booking_amnt` DECIMAL(10,0) NOT NULL,
  `guest_id_fk` INT NOT NULL,
  `property_id_fk` INT NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `host_id_idx` (`host_id` ASC) VISIBLE,
  INDEX `fk_Booking_AnuvindP_GuestLogin_AnuvindP1_idx` (`guest_id_fk` ASC) VISIBLE,
  INDEX `fk_Booking_AnuvindP_Properties_AnuvindP1_idx` (`property_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_Booking_AnuvindP_GuestLogin_AnuvindP1`
    FOREIGN KEY (`guest_id_fk`)
    REFERENCES `mydb`.`GuestLogin_anuvindp` (`guest_id`),
  CONSTRAINT `fk_Booking_AnuvindP_Properties_AnuvindP1`
    FOREIGN KEY (`property_id_fk`)
    REFERENCES `mydb`.`Properties_AnuvindP` (`property_id`),
  CONSTRAINT `host_id`
    FOREIGN KEY (`host_id`)
    REFERENCES `mydb`.`Hostlogin_AnuvindP` (`host_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Review_AnuvindP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Review_AnuvindP` (
  `review_id` INT NOT NULL,
  `overall_experience` VARCHAR(200) NULL DEFAULT NULL,
  `cleanliness_rating` INT NOT NULL,
  `overall_rating` INT NOT NULL,
  `Reviewee_type` VARCHAR(45) NOT NULL,
  `Reviewer_type` VARCHAR(45) NOT NULL,
  `Fk_host_id` INT NOT NULL,
  `Fk_guest_id` INT NOT NULL,
  `Fk_booking_id` INT NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_Review_AnuvindP_HostLogin_AnuvindP1_idx` (`Fk_host_id` ASC) VISIBLE,
  INDEX `fk_Review_AnuvindP_GuestLogin_AnuvindP1_idx` (`Fk_guest_id` ASC) VISIBLE,
  INDEX `fk_Review_AnuvindP_Booking_AnuvindP1_idx` (`Fk_booking_id` ASC) VISIBLE,
  CONSTRAINT `fk_Review_AnuvindP_Booking_AnuvindP1`
    FOREIGN KEY (`Fk_booking_id`)
    REFERENCES `mydb`.`Booking_AnuvindP` (`booking_id`),
  CONSTRAINT `fk_Review_AnuvindP_GuestLogin_AnuvindP1`
    FOREIGN KEY (`Fk_guest_id`)
    REFERENCES `mydb`.`GuestLogin_anuvindp` (`guest_id`),
  CONSTRAINT `fk_Review_AnuvindP_HostLogin_AnuvindP1`
    FOREIGN KEY (`Fk_host_id`)
    REFERENCES `mydb`.`Hostlogin_AnuvindP` (`host_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
